routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|

/* Admin Panel Routes */

Route::group(['prefix' => 'admin', 'middleware' => 'isAdmin'], function () {

	//User Home page.
	Route::get('/index', 'Admin\AdminController@index')->name('admin-index');

	//User management Route.
	Route::get('/user-management', 'Admin\AdminController@usermanagement_index')->name('user-management');

	//User Resource Controller
	Route::resource('users', 'Admin\UserController');

	//Role Resource Controller
	Route::resource('roles', 'Admin\RoleController');

	//Permission Resource Controller
	Route::post('/assign-permission', 'Admin\PermissionController@assign_permission_post')->name('assign-permission-post');

	Route::post('/assign-permission-del', 'Admin\PermissionController@assign_permission_del')->name('assign-permission-del');

	Route::resource('permissions', 'Admin\PermissionController');

	/* Activity Log Routes */

	Route::get('/activity-log', 'Admin\AdminController@activitylog_index')->name('activitylog_index');

	/* Todo List Routes */
	//Todo custom update
	Route::post('/todos_update', 'Admin\TodoController@todos_update')->name('todos_update');

	//Todo custom delete
	Route::post('/todos_delete', 'Admin\TodoController@todos_delete')->name('todos_delete');

	//Task done undone, change status
	Route::post('/task_status', 'Admin\TodoController@task_status')->name('task_status');

	//Task sorting
	Route::post('/task_sort', 'Admin\TodoController@task_sort')->name('task_sort');

	/*Todo Resource*/
	Route::resource('todos', 'Admin\TodoController');

	/* Pages resource */
	Route::resource('pages', 'Admin\PageController');

	/* Analytics Route */
	Route::get('analytics', 'Admin\AnalyticsController@analytics')->name('analytics');

	//Load Admin Subject page
	Route::get('/subjects', 'admin\SubjectController@index')->name('subject_admin');

	//Edit subject-data
	Route::post('/edit-subj-data', 'admin\SubjectController@edit_subj_data')->name('edit_subj_data');
	Route::post('/edit-grade-data', 'admin\SubjectController@edit_grade_data')->name('edit_grade_data');

	//Edit-add data admin subject
	Route::post('/add-edit-subjectdata', 'admin\SubjectController@subject_submit')->name('subject_submit');
	Route::post('/add-edit-gradedata', 'admin\SubjectController@grade_submit')->name('grade_submit');

	//Subject delete
	Route::get('/subject-delete/{id}', 'admin\SubjectController@delete_subject')->name('delete_subject');
	Route::get('/grade-delete/{id}', 'admin\SubjectController@delete_grade')->name('delete_grade');


 Route::get('/chapters', 'admin\ChapterController@index')->name('chapters');
Route::post('/add-edit-chapterdata', 'admin\ChapterController@chapter_submit')->name('chapter_submit');
Route::post('/edit-chapter-data', 'admin\ChapterController@edit_chapter_data')->name('edit_chapter_data');
//Get grade subjects
	Route::post('/get-chapters', 'Admin\TestController@get_subject_chapters')->name('get_subject_chapters');


	//Listing Of Job Requests
	Route::get('/job-requests', 'Admin\JobController@index')->name('job_requests');
	Route::get('/manage-reviews', 'Admin\AdminController@profile_reviews')->name('profile_reviews');
	Route::get('/manage-grades', 'Admin\AdminController@profile_grades')->name('profile_grades');
	Route::get('/review-delete/{id}', 'Admin\AdminController@review_delete')->name('review_delete');

	Route::get('/accept_review/{id}/', ["as" => "accept-review","uses" => "Admin\AdminController@accept_review"]);
	Route::get('/reject_review/{id}/', ["as" => "reject-review", "uses" => "Admin\JobController@reject_review"]);


	Route::get('/job_boards', 'Admin\JobController@job_boards')->name('job_boards');
	Route::get('/job-requests-delete/{id}', 'Admin\JobController@delete_job_request')->name('delete_job_request');
	Route::get('/job-boards-delete/{id}', 'Admin\JobController@delete_job_board')->name('delete_job_board');
	Route::post('/edit-job-request-data', 'Admin\JobController@edit_job_request')->name('edit_job_request');
	Route::get('/accept_job_request/{id}/', ["as" => "accept-job-request","uses" => "Admin\JobController@accept_job_request"]);

	Route::get('/accept_job_board/{id}/', ["as" => "accept_job_board","uses" => "Admin\JobController@accept_job_board"]);
	Route::get('/reject_job_request/{id}/', ["as" => "reject-job-request", "uses" => "Admin\JobController@reject_job_request"]);
	Route::get('/reject_job_board/{id}/', ["as" => "reject_job_board", "uses" => "Admin\JobController@reject_job_board"]);
	// transactions
	Route::get('transactions', 'Admin\AdminController@transactions')->name('admin_transactions');
	Route::get('withdraws', 'Admin\AdminController@withdraws')->name('admin_withdraws');
	Route::get('transaction_details/{id}', 'Admin\AdminController@transaction_detail')->name('admin_transaction_detail');


	// transactions
	Route::get('booking', 'Admin\AdminController@booking')->name('admin_booking');
	

	//Test Routes
	Route::get('/add-test', 'Admin\TestController@add_testindex')->name('admin_addtest_index');

	Route::get('/test-list', 'Admin\TestController@test_listing')->name('admin_testlist');

   
    Route::get('/payment-detection/{id}', 'admin\PayController@payment_detection')->name('payment_detection');

    Route::get('/destroy-withdraw/{id}', 'admin\PayController@destroy_withdraw')->name('destroy_withdraw');
	///Route::get('/test-delete', 'Admin\TestController@destroy_admtest')->name('admin_testdelete');

	Route::get('/test-delete/{id}','Admin\TestController@destroy_admtest')->name('test-delete');

	//Get grade subjects
	Route::post('/get-subjects', 'Admin\TestController@get_grade_subjects')->name('get_grade_subjects');

	//Post test mcq
	Route::post('/add-test', 'Admin\TestController@admin_addtest')->name('admin_addtest');

	//Career - Add Job
	Route::get('/add-job', 'Admin\JobController@admin_addjob')->name('admin_addjob');

	//Career - Save Job
	Route::post('/save-job', 'Admin\JobController@care_jobs_save')->name('care_jobs_save');

	//Career - All Jobs
	Route::get('/all-jobs', 'Admin\JobController@care_all_jobs')->name('care_all_jobs');

	//Career - Single Job
	Route::get('/career-job/{jobid}', 'Admin\JobController@career_job_detail')->name('career_job_detail');

	//Edit Single Career Job
	Route::get('/career-edit-job/{jobid}', 'Admin\JobController@career_job_editIndex')->name('career_job_editIndex');

	//Edit Single Career Job Post
	Route::post('/career-job', 'Admin\JobController@career_job_editIndex_post')->name('career_job_editIndex_post');

	//Delete Single Career Job
	Route::get('/career-job-delete/{jobid}', 'Admin\JobController@career_job_delete')->name('career_job_delete');


	//Career - All Applications
	Route::get('/job-applications', 'Admin\JobController@care_applications_jobs')->name('care_applications_jobs');

	//Single Application detail Page
	Route::get('/job-application-detail/{appid}', 'Admin\JobController@application_detail')->name('application_detail');

});

	//Admin Login Authentication
	Route::get('/admin-login', 'Admin\AuthController@login_index')->name('adminlogin_index');


	Route::post('/admin-login', 'Admin\AuthController@login_post')->name('admin_login_post');


	Route::get('downlaod_resume/{id}','Admin\JobController@get_resume')->name('get_resume');

	//Logout
	Route::get('/admin-logout', 'Admin\AuthController@logout')->name('logout');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Home Controller Route */
    Route::get('/', 'HomeController@index')->name('home');

/* Authentication Routes */
    Route::group(['middleware' => 'guest'], function () {

	Route::get('/signin', 'AuthenticationController@login_index')->name('signin');

	Route::get('/signup/', 'AuthenticationController@register_index')->name('signup');

	Route::post('/user_register/ajax',array('as'=>'user_register.ajax','uses'=>'AuthenticationController@stateForCountryAjax'));

	Route::get('/forget_password', 'HomeController@forget_password')->name('forget_password_form');

	Route::post('/send_forget_email', 'AuthenticationController@send_forget_email')->name('send_forget_email');

	Route::get('/set_new_password/{token}', 'AuthenticationController@set_new_password')->name('set_new_password');

	Route::post('/new_password/{email}', 'AuthenticationController@new_password')->name('new_password');

	Route::get('register/verify/{token}', 'AuthenticationController@verify')->name('verified_email');

	//Student and Teacher register
	Route::post('/register', 'AuthenticationController@register_post')->name('register_post');

	//Login Post
	Route::post('/login', 'AuthenticationController@login_post')->name('login_post');

	Route::get('full_time_tutor_form','HomeController@full_time_tutor')->name('full_time_tutor');

	Route::post('full_time_email','HomeController@full_time_email')->name('full_time_email');
});

Route::get('faqs','HomeController@faqs')->name('faqs');
Route::get('referral','HomeController@referral')->name('referral');


Route::post('write_testimonial','HomeController@write_testimonial')->name('write_testimonial');

//Logout Route
Route::get('/logout',  'AuthenticationController@logout_user')->name('logout_user');

// email subscribe
Route::post('/subscribe','HomeController@subscribe')->name('subscribe');

//How it works
Route::get('/how-it-works', 'HomeController@how_it_works')->name('how_it_works');

// lessons_grade
//Route::get('/lessons_grade', 'HomeController@lessons_grade')->name('lessons_grade');

//Tutor find jobs
Route::get('/find-job', 'HomeController@find_tutor')->name('find_tutor');

Route::post('/filter_register/ajax',array('as'=>'filter_register.ajax','uses'=>'HomeController@filterForCountryAjax'));

//Tutor filter jobs
Route::get('/find-job-filter', 'HomeController@filter_jobs')->name('filter_jobs');

     //Tutor profile

Route::get('/profile/{name}', 'Tutor\TutorController@tutor_profile')->name('tutor_profile');

Route::get('/tutor_earnings_details/{id}','Tutor\TutorController@tutor_earnings_details')->name('tutor_earnings_details');
//Fulltime Tutor
Route::get('/fulltime-tutor', 'HomeController@fulltime_tutor')->name('fulltime_tutor');

//Publications
Route::get('/publications', 'HomeController@publications')->name('publications');

//aboutus
Route::get('/aboutus', 'HomeController@aboutus')->name('aboutus');
Route::get('/terms', 'HomeController@terms')->name('terms');
Route::get('/privacy', 'HomeController@privacy')->name('privacy');
Route::get('/contactus', 'HomeController@contactus')->name('contactus');
Route::post('/contactus_post', 'HomeController@contactus_post')->name('contactus_post');
Route::get('/testimonials', 'HomeController@testimonials')->name('testimonials');
Route::get('/faq', 'HomeController@faq')->name('faq');

// Route::post('/home_tutor_filter','HomeController@home_tutor_filter')->name('home_tutor_filter');


/* Dashboard Controller Routes */
Route::group(['middleware' => 'auth'], function () {

	Route::get('/dashboard/home', 'DashboardController@index')->name('dashboard_index');

	Route::group(['middleware' => 'isTutor'], function () {

		//Get tutor subjects
		Route::get('/subjects','DashboardController@subjects')->name('subjects');

		//insert tutor selected subject
		Route::post('/tutor_subject','DashboardController@tutor_subject')->name('tutor_subject');

		//Delete subject
		Route::get('/delete-subject/{id}','DashboardController@subjDel')->name('subjDel');

	});

	Route::get('chat_box','MessageController@user_list')->name('chat_box');
	Route::get('/edit-profile', 'ProfileController@edit_dashboard')->name('edit_dashboard');

	Route::post('/profile_register/ajax',array('as'=>'profile_register.ajax','uses'=>'ProfileController@editcityForCountryAjax'));

	//Edit profile post
	Route::post('/edit_profile', 'ProfileController@edit_profile')->name('edit_profile');

	/* Change existing Password */

	//Change existing password view
	Route::get('/settings/change-password/{id}', 'DashboardController@edit_pass_view')->name('change_pass_index');

	// change_newpassword
	Route::post('/settings/change-password/{id}', 'DashboardController@change_newpassword')->name('change_newpassword');

	//Change existing password post
	Route::post('/settings/change-password', 'DashboardController@edit_pass_post')->name('change_pass_post');

	//Ajax profile upload
	Route::post('imageUpload',['as'=>'imageUpload','uses'=>'ProfileController@imageUpload']);

	/* Job Controllers Routes */

	//Post Job view page
	Route::get('/post-job', 'JobController@student_postJob')->name('postjob_view');
	Route::get('/post-job-list', 'JobController@student_postJob_list')->name('post-job-list');
	Route::get('/post-job-detail/{id}', 'JobController@student_postJob_detail')->name('post-job-detail');

	Route::get('/find-job-detail', 'JobController@find_tutor_detail')->name('find_tutor_detail');
	//Post Job request page
	Route::post('/request-job', 'JobController@request_job')->name('request_job');
	Route::post('/post_rating', 'JobController@post_rating')->name('post_rating');

	//Student Reply to tutor on Student Job
	Route::post('/request-reply_tutor', 'JobController@reply_tutor')->name('reply_tutor');

	Route::post('/post-job', 'JobController@student_postJob_req')->name('student_postJob_req');

	/* Job Booking Lesson Routes */
	Route::get('/book-lesson/{jobid}','BookingController@booking_view')->name('booking_index');



	//Student Book Lesson
	//Book Lesson By Student
	Route::post('/book-lesson', 'BookingController@student_booklesson')->name('student_booklesson');

	//Booked Lessons
	Route::get('/bookings', 'DashboardController@bookings_list')->name('bookings_list');

	//Cancel Booking
	Route::get('/booking-cancel/{id}', 'BookingController@booking_cancel')->name('booking_cancel');

	//Accept Booking - by Tutor
	Route::get('/booking-accept/{id}', 'BookingController@booking_status')->name('booking_accept');

	//Accept Booking - by Tutor
	Route::get('/booking-reject/{id}', 'BookingController@booking_status')->name('booking_reject');

	Route::get('/book_refer/{id}','BookingController@booking_reffer_view')->name('book_refer');

Route::post('book_refer_insert','BookingController@refer_bookrequest')->name('book_refer_insert'); 
	///Route::post('/book_refer_insert','BookingController@refer_bookrequest');

	//Booking details
	Route::get('/booking_detail/{id}', 'BookingController@booking_detail')->name('booking_detail');

	//Tutor earnings
	Route::get('/tutor-earnings', 'Tutor\TutorController@tutor_earnings')->name('tutor_earnings');

	/* Pre test Routes */

	//Pre test payment route page for students
	Route::get('/pre-test-payment/{name?}', 'Student\StudentController@pre_test_payment_index')->name('pre_test_payment_index');

	Route::get('/pay-pretest-student', 'Paypal\StudentPayment@pay_pretest_student')->name('pay_pretest_student');

	// Route::get('getPretestDone', 'Paypal\StudentPayment@getPreTestDone');
	// Route::get('getPreTestCancel', 'Paypal\StudentPayment@getPreTestCancel');

	//Pre test routes
	Route::get('/pre-test', 'Test\TestController@student_pretest')->name('student_pretest');

Route::get('/my_result', 'DashboardController@my_result')->name('my_result');


	Route::get('invite_friend','DashboardController@invite_friend')->name('invite_friend');
	
	Route::post('invite_request','DashboardController@invite_request')->name('invite_request');
});

Route::get('/contact_admin', 'DashboardController@ContactAdmin')->name('contact_admin');


Route::post('depositWallet', 'Paypal\StudentPayment@depositWallet')->name('depositWallet');


Route::get('getDone', 'Paypal\StudentPayment@getDone');
Route::get('getCancel', 'Paypal\StudentPayment@getCancel');
Route::get('my_transactions', 'ProfileController@my_transactions')->name('my_transactions');
Route::get('transaction_detail/{id}', 'ProfileController@transaction_detail')->name('transaction_detail');
Route::post('walletWithdraw', 'ProfileController@walletWithdraw')->name('walletWithdraw');
Route::get('my_wallet', 'ProfileController@my_balance')->name('my_balance');

//Accept withdraw by Admin
Route::get('accept-withdraw/{id}', 'Paypal\StudentPayment@accept_withdraw')->name('accept_withdraw');


/* Unauthorized Access Routes */
Route::get('/401', 'HomeController@unauthorized')->name('unauthorized');

/* Error Route */
Route::get('/error/{message}', 'HomeController@error')->name('error');

//Tutor Search
Route::get('/tutor-search/{flag?}/{subject?}/{id?}', 'Tutor\TutorController@index')->name('tutors_listing');
Route::get('/tutor-search-ajax/', 'Tutor\TutorController@tutor_search_ajax');
Route::Post('/contact_tutor_email/', 'Tutor\TutorController@contact_tutor_email')->name('contact_tutor_email');
Route::get('/review', 'extraController@review')->name('review');


Route::get('scheduling', function () {
    return view('dashboard.scheduling');
});

//Ajax route for getting chat messages
Route::post('chat_messages','MessageController@chat_messages')->name('chat_messages');

Route::get('create_schedule','Tutor\SchedulingController@create_schedule')->name('create_schedule');

resources/views/admin/user/create.blade.php
@extends('admin.admin-app')
@section('content')

<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        User Panel
        <small>- Add User</small>
      </h1>
    </section>
    @include('partials.error_section')
    @foreach($errors->all() as $erroring)
                  <li>{{$erroring}}  </li>
                  @endforeach
    <!-- Main content -->
        <section class="content">
     <div class="row">
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Add User</h3>
              @include('admin.partials.error_section')
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" action="{{route('users.store')}}" method="post">
              <div class="box-body">
                <div class="form-group">
                  <label for="">First Name</label>
                  <input type="text" class="form-control" name="first_name" placeholder="Enter First name">
                </div>

                <div class="form-group">
                  <label for="">Last Name</label>
                  <input type="text" class="form-control" name="last_name" placeholder="Enter last name">
                </div>

                <div class="form-group">
                  <label for="exampleInputUsername">Username</label>
                  <input type="text" class="form-control" name="username" id="exampleInputUsername" placeholder="Enter email">
                </div>

                <div class="form-group">
                  <label for="">Phone no</label>
                  <input type="text" class="form-control" name="phonenum1" placeholder="Enter phone no">
                </div>

                <div class="form-group">
                  <label for="exampleInputEmail1">Email</label>
                  <input type="email" class="form-control" name="email" id="exampleInputEmail1" placeholder="Enter email">
                </div>

                <div class="form-group">
                  <label for="exampleInputPassword1">Password</label>
                  <input type="password" class="form-control" name="password" id="exampleInputPassword1" placeholder="Password">
                </div>

                <div class="form-group">
                  <label for="exampleInputQualification">Qualifications</label>
                  <input type="text" class="form-control" name="qualifications" id="exampleInputqualifications" placeholder="Qualifications">
                </div>

                <div class="form-group">
                  <label for="exampleInputQualifications">Qualifications From</label>
                  <input type="text" class="form-control" name="qualification_from" id="exampleInputqualifications_form" placeholder="Qualifications From">
                </div>
                
                <div class="form-group profile_form">
                  <label for="exampleInputRate">Rates / Hour <span>*</span></label>
                  <input type="text" class="form-control span3" name="tution_per_hour" id="exampleInputRate" value="{{ isset($user->tution_per_hour) ? $user->tution_per_hour : '' }}"required>
                </div>
                <div class="form-group profile_form">
                  <label for="Bio">Bio </label>
                  <br>
                  <textarea name="bio" class="span3 form-control" ></textarea>
                </div>
                <div class="form-group profile_form">
                  <label for="exampleInputGender">Gender<span>*</span></label>
                  <select name="gender" class="form-control">
                    <option value="male">Male</option>
                    <option value="female">female</option>
                  </select>
                </div>
                <div class="form-group profile_form">
                  <label for="exampleInputage">Age<span>*</span></label>
                  <input type="text" name="age" id="exampleInputage" value="" class="form-control span3" required>
                </div>
                <div class="form-group"  class="form-control">
                  <label for="exampleInputPassword1">User role</label>
                  <select name="user_role" class="form-control">
                    @foreach($roles as $role)
                     <option value="{{$role->id}}">{{$role->name}}</option>
                    @endforeach
                  </select>
                </div>

                <div class="form-group"  class="form-control">
                  <label for="exampleInputPassword1">Statuses</label>
                  <select name="status_id" class="form-control">
                    @foreach($statuses as $status)
                     <option value="{{$status->id}}">{{$status->status}}</option>
                    @endforeach
                  </select>
                </div>

              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <input type="hidden" name="_token" value="{{Session::token()}}">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
          <!-- /.box -->

        </div>

    </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

@endsection

resources/views/admin/user/index.blade.php
@extends('admin.admin-app')
@section('content')

<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        User Panel
        <small>- Users </small>
      </h1>
    </section>

    <!-- Main content -->
        <section class="content">    
     <div class="row">


      <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Users List</h3>
                @include('admin.partials.error_section')              
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="userTable" class="table table-bordered table-hover">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Email</th>
                      <th>Role</th>
                      <th>Status</th>
                      <th>Account</th>
                      <th>Action</th>                    
                    </tr>
                  </thead>
                  <tbody>
                    @foreach($users as $user)
                      <tr>
                        <td>{{$user->first_name}}</td>
                        <td>{{$user->email}}</td>
                        <td>{{$user->display_name}}</td>
                        <td>{{$user->status}}</td>
                        <td>@if($user->verified == 1) Verified @elseif ($user->verified == 0) unVerified @endif</td>
                        <td><a href="{{route('users.edit', ['id' => $user->id])}}"><button type="button" class="btn btn-info">Edit</button></a>
                        <a href="{{route('users.show', ['id' => $user->id])}}"><button type="button" class="btn btn-info f_view">View</button></a>
                        <form id="deleteUser" onsubmit="return confirm('Do you really want to delete?')" action="{{route('users.destroy', ['id' => $user->id])}}" method="post" class="f_form">
                          {{ method_field('DELETE') }}
                          <input type="hidden" name="_token" value="{{Session::token()}}">
                          <button type="submit" class="btn btn-danger f_view">Delete</button>
                        </form>

                        </td>
                      </tr>                
                    @endforeach              
                  </tbody>

              </table>
            </div>
        </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

@endsection

resources/views/admin/user/show.blade.php
@extends('admin.admin-app')
@section('content')

<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        User Panel
      </h1>
    </section>

    <!-- Main content -->
        <section class="content">
           <div class="row">
              <div class="col-md-6">
                <!-- general form elements -->

                  <div class="box box-primary user_info">
                    <div class="row">
                      <div class="col-md-12 col-xs-12">
                      <p>
                        <span>
                          <i class="fa fa-user"></i> Name :
                        </span>
                        <span>{{ $user->name }}</span>
                      </p>
                      <p>
                        <span>
                          <i class="fa fa-envelope"></i> Email :
                        </span>
                        <span>{{ $user->email }}</span>
                      </p>
                      <p>
                        <span>
                          <i class="fa fa-tasks"></i> Role :
                        </span>
                        <span>{{ $user->display_name }}</span>
                      </p>
                      <p>
                        <span>
                          <i class="fa fa-users"></i> User Name :
                        </span>
                        <span>{{ $user->username }}</span>
                      </p>
                      <p>
                        <span>
                          <i class="fa fa-plus-square"></i> Bio :
                        </span>
                        <span>{{ $user->bio }}</span>
                      </p>
                      <p>
                        <span>
                          <i class="fa fa-clock-o"></i> Tution Per Hour :
                        </span>
                        <span>{{ $user->tution_per_hour }}</span>
                      </p>
                      <p>
                        <span>
                          <i class="fa fa-transgender"></i> Gender :
                        </span>
                        <span>{{ $user->gender }}</span>
                      </p>

                    </div>
                    </div>
                  </div>
                <!-- /.box -->

              </div>

            </div>
        </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

@endsection